build:
	docker build -t kostaleonard/fortune:args .

run:
	docker run --name fortune-container-args kostaleonard/fortune:args

run_arg:
	docker run --name fortune-container-args kostaleonard/fortune:args 15

stop:
	docker stop fortune-container-args

push:
	docker push kostaleonard/fortune:args
